package bullhorn

type Candidate struct {
	Id               int `json:"id"`
	ActivePlacements struct {
		Total int   `json:"total"`
		Data  []int `json:"data"`
	} `json:"activePlacements"`
	Address struct {
		Address1    interface{} `json:"address1"`
		Address2    interface{} `json:"address2"`
		City        interface{} `json:"city"`
		CountryCode string      `json:"countryCode"`
		CountryID   int         `json:"countryID"`
		CountryName string      `json:"countryName"`
		State       interface{} `json:"state"`
		Timezone    interface{} `json:"timezone"`
		Zip         interface{} `json:"zip"`
	} `json:"address"`
	Branch          interface{} `json:"branch"`
	BusinessSectors struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"businessSectors"`
	CanEnterTime    bool        `json:"canEnterTime"`
	CandidateSource interface{} `json:"candidateSource"`
	Categories      struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"categories"`
	Category struct {
		Id   int    `json:"id"`
		Name string `json:"name"`
	} `json:"category"`
	CertificationList struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"certificationList"`
	Certifications             interface{} `json:"certifications"`
	ClientCorporationBlackList struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"clientCorporationBlackList"`
	ClientCorporationWhiteList struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"clientCorporationWhiteList"`
	Comments                    string      `json:"comments"`
	CompanyName                 interface{} `json:"companyName"`
	CompanyURL                  interface{} `json:"companyURL"`
	CustomDate1                 interface{} `json:"customDate1"`
	CustomDate10                interface{} `json:"customDate10"`
	CustomDate11                interface{} `json:"customDate11"`
	CustomDate12                interface{} `json:"customDate12"`
	CustomDate13                interface{} `json:"customDate13"`
	CustomDate2                 interface{} `json:"customDate2"`
	CustomDate3                 interface{} `json:"customDate3"`
	CustomDate4                 interface{} `json:"customDate4"`
	CustomDate5                 interface{} `json:"customDate5"`
	CustomDate6                 interface{} `json:"customDate6"`
	CustomDate7                 interface{} `json:"customDate7"`
	CustomDate8                 interface{} `json:"customDate8"`
	CustomDate9                 interface{} `json:"customDate9"`
	CustomEncryptedText1        interface{} `json:"customEncryptedText1"`
	CustomEncryptedText10       interface{} `json:"customEncryptedText10"`
	CustomEncryptedText2        interface{} `json:"customEncryptedText2"`
	CustomEncryptedText3        interface{} `json:"customEncryptedText3"`
	CustomEncryptedText4        interface{} `json:"customEncryptedText4"`
	CustomEncryptedText5        interface{} `json:"customEncryptedText5"`
	CustomEncryptedText6        interface{} `json:"customEncryptedText6"`
	CustomEncryptedText7        interface{} `json:"customEncryptedText7"`
	CustomEncryptedText8        interface{} `json:"customEncryptedText8"`
	CustomEncryptedText9        interface{} `json:"customEncryptedText9"`
	CustomFloat1                interface{} `json:"customFloat1"`
	CustomFloat10               interface{} `json:"customFloat10"`
	CustomFloat11               interface{} `json:"customFloat11"`
	CustomFloat12               interface{} `json:"customFloat12"`
	CustomFloat13               interface{} `json:"customFloat13"`
	CustomFloat14               interface{} `json:"customFloat14"`
	CustomFloat15               interface{} `json:"customFloat15"`
	CustomFloat16               interface{} `json:"customFloat16"`
	CustomFloat17               interface{} `json:"customFloat17"`
	CustomFloat18               interface{} `json:"customFloat18"`
	CustomFloat19               interface{} `json:"customFloat19"`
	CustomFloat2                interface{} `json:"customFloat2"`
	CustomFloat20               interface{} `json:"customFloat20"`
	CustomFloat21               interface{} `json:"customFloat21"`
	CustomFloat22               interface{} `json:"customFloat22"`
	CustomFloat23               interface{} `json:"customFloat23"`
	CustomFloat3                interface{} `json:"customFloat3"`
	CustomFloat4                interface{} `json:"customFloat4"`
	CustomFloat5                interface{} `json:"customFloat5"`
	CustomFloat6                interface{} `json:"customFloat6"`
	CustomFloat7                interface{} `json:"customFloat7"`
	CustomFloat8                interface{} `json:"customFloat8"`
	CustomFloat9                interface{} `json:"customFloat9"`
	CustomInt1                  interface{} `json:"customInt1"`
	CustomInt10                 interface{} `json:"customInt10"`
	CustomInt11                 interface{} `json:"customInt11"`
	CustomInt12                 interface{} `json:"customInt12"`
	CustomInt13                 interface{} `json:"customInt13"`
	CustomInt14                 interface{} `json:"customInt14"`
	CustomInt15                 interface{} `json:"customInt15"`
	CustomInt16                 interface{} `json:"customInt16"`
	CustomInt17                 interface{} `json:"customInt17"`
	CustomInt18                 interface{} `json:"customInt18"`
	CustomInt19                 interface{} `json:"customInt19"`
	CustomInt2                  interface{} `json:"customInt2"`
	CustomInt20                 interface{} `json:"customInt20"`
	CustomInt21                 interface{} `json:"customInt21"`
	CustomInt22                 interface{} `json:"customInt22"`
	CustomInt23                 interface{} `json:"customInt23"`
	CustomInt3                  interface{} `json:"customInt3"`
	CustomInt4                  interface{} `json:"customInt4"`
	CustomInt5                  interface{} `json:"customInt5"`
	CustomInt6                  interface{} `json:"customInt6"`
	CustomInt7                  interface{} `json:"customInt7"`
	CustomInt8                  interface{} `json:"customInt8"`
	CustomInt9                  interface{} `json:"customInt9"`
	CustomText1                 string      `json:"customText1"`
	CustomText10                interface{} `json:"customText10"`
	CustomText11                interface{} `json:"customText11"`
	CustomText12                interface{} `json:"customText12"`
	CustomText13                interface{} `json:"customText13"`
	CustomText14                interface{} `json:"customText14"`
	CustomText15                interface{} `json:"customText15"`
	CustomText16                interface{} `json:"customText16"`
	CustomText17                interface{} `json:"customText17"`
	CustomText18                interface{} `json:"customText18"`
	CustomText19                interface{} `json:"customText19"`
	CustomText2                 interface{} `json:"customText2"`
	CustomText20                interface{} `json:"customText20"`
	CustomText21                interface{} `json:"customText21"`
	CustomText22                interface{} `json:"customText22"`
	CustomText23                interface{} `json:"customText23"`
	CustomText24                interface{} `json:"customText24"`
	CustomText25                interface{} `json:"customText25"`
	CustomText26                interface{} `json:"customText26"`
	CustomText27                interface{} `json:"customText27"`
	CustomText28                interface{} `json:"customText28"`
	CustomText29                interface{} `json:"customText29"`
	CustomText3                 string      `json:"customText3"`
	CustomText30                interface{} `json:"customText30"`
	CustomText31                interface{} `json:"customText31"`
	CustomText32                interface{} `json:"customText32"`
	CustomText33                interface{} `json:"customText33"`
	CustomText34                interface{} `json:"customText34"`
	CustomText35                interface{} `json:"customText35"`
	CustomText36                interface{} `json:"customText36"`
	CustomText37                interface{} `json:"customText37"`
	CustomText38                interface{} `json:"customText38"`
	CustomText39                interface{} `json:"customText39"`
	CustomText4                 []string    `json:"customText4"`
	CustomText40                interface{} `json:"customText40"`
	CustomText5                 []string    `json:"customText5"`
	CustomText6                 interface{} `json:"customText6"`
	CustomText7                 interface{} `json:"customText7"`
	CustomText8                 interface{} `json:"customText8"`
	CustomText9                 interface{} `json:"customText9"`
	CustomTextBlock1            interface{} `json:"customTextBlock1"`
	CustomTextBlock10           interface{} `json:"customTextBlock10"`
	CustomTextBlock2            interface{} `json:"customTextBlock2"`
	CustomTextBlock3            interface{} `json:"customTextBlock3"`
	CustomTextBlock4            interface{} `json:"customTextBlock4"`
	CustomTextBlock5            interface{} `json:"customTextBlock5"`
	CustomTextBlock6            interface{} `json:"customTextBlock6"`
	CustomTextBlock7            interface{} `json:"customTextBlock7"`
	CustomTextBlock8            interface{} `json:"customTextBlock8"`
	CustomTextBlock9            interface{} `json:"customTextBlock9"`
	DateAdded                   int64       `json:"dateAdded"`
	DateAvailable               interface{} `json:"dateAvailable"`
	DateAvailableEnd            interface{} `json:"dateAvailableEnd"`
	DateI9Expiration            interface{} `json:"dateI9Expiration"`
	DateLastComment             interface{} `json:"dateLastComment"`
	DateLastModified            int64       `json:"dateLastModified"`
	DateLastPayrollProviderSync interface{} `json:"dateLastPayrollProviderSync"`
	DateNextCall                interface{} `json:"dateNextCall"`
	DateOfBirth                 interface{} `json:"dateOfBirth"`
	DayRate                     int         `json:"dayRate"`
	DayRateLow                  interface{} `json:"dayRateLow"`
	DegreeList                  interface{} `json:"degreeList"`
	Description                 interface{} `json:"description"`
	DesiredLocations            interface{} `json:"desiredLocations"`
	Disability                  interface{} `json:"disability"`
	EducationDegree             interface{} `json:"educationDegree"`
	Educations                  struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"educations"`
	Email                             string      `json:"email"`
	Email2                            interface{} `json:"email2"`
	Email3                            interface{} `json:"email3"`
	EmployeeType                      string      `json:"employeeType"`
	EmploymentPreference              interface{} `json:"employmentPreference"`
	EstaffGUID                        interface{} `json:"estaffGUID"`
	Ethnicity                         interface{} `json:"ethnicity"`
	Experience                        int         `json:"experience"`
	ExternalID                        interface{} `json:"externalID"`
	Fax                               interface{} `json:"fax"`
	Fax2                              interface{} `json:"fax2"`
	Fax3                              interface{} `json:"fax3"`
	FederalAddtionalWitholdingsAmount interface{} `json:"federalAddtionalWitholdingsAmount"`
	FederalExemptions                 interface{} `json:"federalExemptions"`
	FederalExtraWithholdingAmount     interface{} `json:"federalExtraWithholdingAmount"`
	FederalFilingStatus               interface{} `json:"federalFilingStatus"`
	FileAttachments                   struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"fileAttachments"`
	FirstName     string      `json:"firstName"`
	Gender        interface{} `json:"gender"`
	HourlyRate    int         `json:"hourlyRate"`
	HourlyRateLow interface{} `json:"hourlyRateLow"`
	I9OnFile      interface{} `json:"i9OnFile"`
	Interviews    struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"interviews"`
	IsAnonymized      bool        `json:"isAnonymized"`
	IsDayLightSavings bool        `json:"isDayLightSavings"`
	IsDeleted         bool        `json:"isDeleted"`
	IsEditable        bool        `json:"isEditable"`
	IsExempt          interface{} `json:"isExempt"`
	IsLockedOut       bool        `json:"isLockedOut"`
	LastName          string      `json:"lastName"`
	Leads             struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"leads"`
	LinkedPerson                    interface{} `json:"linkedPerson"`
	LocalAddtionalWitholdingsAmount interface{} `json:"localAddtionalWitholdingsAmount"`
	LocalExemptions                 interface{} `json:"localExemptions"`
	LocalFilingStatus               interface{} `json:"localFilingStatus"`
	LocalTaxCode                    interface{} `json:"localTaxCode"`
	Locations                       struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"locations"`
	MaritalStatus  interface{} `json:"maritalStatus"`
	MassMailOptOut bool        `json:"massMailOptOut"`
	MasterUserID   interface{} `json:"masterUserID"`
	MiddleName     interface{} `json:"middleName"`
	MigrateGUID    interface{} `json:"migrateGUID"`
	Mobile         string      `json:"mobile"`
	Name           string      `json:"name"`
	NamePrefix     interface{} `json:"namePrefix"`
	NameSuffix     interface{} `json:"nameSuffix"`
	NickName       interface{} `json:"nickName"`
	Notes          struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"notes"`
	NumCategories                   int         `json:"numCategories"`
	NumOwners                       int         `json:"numOwners"`
	Occupation                      interface{} `json:"occupation"`
	OnboardingDocumentReceivedCount int         `json:"onboardingDocumentReceivedCount"`
	OnboardingDocumentSentCount     int         `json:"onboardingDocumentSentCount"`
	OnboardingPercentComplete       int         `json:"onboardingPercentComplete"`
	OnboardingReceivedSent          struct {
		OnboardingDocumentReceivedCount int `json:"onboardingDocumentReceivedCount"`
		OnboardingDocumentSentCount     int `json:"onboardingDocumentSentCount"`
	} `json:"onboardingReceivedSent"`
	OnboardingStatus      interface{} `json:"onboardingStatus"`
	OtherDeductionsAmount interface{} `json:"otherDeductionsAmount"`
	OtherIncomeAmount     interface{} `json:"otherIncomeAmount"`
	Owner                 struct {
		Id        int    `json:"id"`
		FirstName string `json:"firstName"`
		LastName  string `json:"lastName"`
	} `json:"owner"`
	Pager                  interface{} `json:"pager"`
	PaperWorkOnFile        interface{} `json:"paperWorkOnFile"`
	Password               string      `json:"password"`
	PayrollClientStartDate interface{} `json:"payrollClientStartDate"`
	PayrollStatus          interface{} `json:"payrollStatus"`
	PersonSubtype          string      `json:"personSubtype"`
	Phone                  interface{} `json:"phone"`
	Phone2                 interface{} `json:"phone2"`
	Phone3                 interface{} `json:"phone3"`
	Placements             struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"placements"`
	PreferredContact string `json:"preferredContact"`
	PrimarySkills    struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"primarySkills"`
	RecentClientList interface{} `json:"recentClientList"`
	References       struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"references"`
	ReferredBy       interface{} `json:"referredBy"`
	ReferredByPerson interface{} `json:"referredByPerson"`
	Salary           int         `json:"salary"`
	SalaryLow        interface{} `json:"salaryLow"`
	SecondaryAddress struct {
		Address1    interface{} `json:"address1"`
		Address2    interface{} `json:"address2"`
		City        interface{} `json:"city"`
		State       interface{} `json:"state"`
		Zip         interface{} `json:"zip"`
		CountryID   int         `json:"countryID"`
		CountryName string      `json:"countryName"`
		CountryCode string      `json:"countryCode"`
	} `json:"secondaryAddress"`
	SecondaryOwners struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"secondaryOwners"`
	SecondarySkills struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"secondarySkills"`
	Sendouts struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"sendouts"`
	Shifts struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"shifts"`
	SkillSet    interface{} `json:"skillSet"`
	Source      string      `json:"source"`
	Specialties struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"specialties"`
	Ssn                             interface{} `json:"ssn"`
	StateAddtionalWitholdingsAmount interface{} `json:"stateAddtionalWitholdingsAmount"`
	StateExemptions                 interface{} `json:"stateExemptions"`
	StateFilingStatus               interface{} `json:"stateFilingStatus"`
	Status                          string      `json:"status"`
	Submissions                     struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"submissions"`
	Tasks struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"tasks"`
	TaxID      interface{} `json:"taxID"`
	TaxState   interface{} `json:"taxState"`
	Tearsheets struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"tearsheets"`
	TimeZoneOffsetEST         int         `json:"timeZoneOffsetEST"`
	TobaccoUser               interface{} `json:"tobaccoUser"`
	TotalDependentClaimAmount interface{} `json:"totalDependentClaimAmount"`
	TravelLimit               int         `json:"travelLimit"`
	TravelMethod              interface{} `json:"travelMethod"`
	TwoJobs                   interface{} `json:"twoJobs"`
	Type                      interface{} `json:"type"`
	UserDateAdded             int64       `json:"userDateAdded"`
	UserType                  interface{} `json:"userType"`
	Username                  string      `json:"username"`
	Veteran                   interface{} `json:"veteran"`
	WebResponses              struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"webResponses"`
	WillRelocate   bool `json:"willRelocate"`
	WorkAuthorized bool `json:"workAuthorized"`
	WorkHistories  struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"workHistories"`
	WorkPhone interface{} `json:"workPhone"`
}
