package bullhorn

type Placement struct {
	Id           int `json:"id"`
	Appointments struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"appointments"`
	ApprovedChangeRequests       int         `json:"approvedChangeRequests"`
	ApprovingClientContact       interface{} `json:"approvingClientContact"`
	BackupApprovingClientContact interface{} `json:"backupApprovingClientContact"`
	BenefitGroup                 interface{} `json:"benefitGroup"`
	BillingClientContact         interface{} `json:"billingClientContact"`
	BillingFrequency             interface{} `json:"billingFrequency"`
	BonusPackage                 interface{} `json:"bonusPackage"`
	Branch                       interface{} `json:"branch"`
	CanEnterTime                 bool        `json:"canEnterTime"`
	Candidate                    struct {
		Id        int    `json:"id"`
		FirstName string `json:"firstName"`
		LastName  string `json:"lastName"`
	} `json:"candidate"`
	ChangeRequests struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"changeRequests"`
	ClientBillRate interface{} `json:"clientBillRate"`
	ClientContact  struct {
		Id        int    `json:"id"`
		FirstName string `json:"firstName"`
		LastName  string `json:"lastName"`
	} `json:"clientContact"`
	ClientCorporation struct {
		Id   int    `json:"id"`
		Name string `json:"name"`
	} `json:"clientCorporation"`
	ClientOvertimeRate interface{} `json:"clientOvertimeRate"`
	Comments           interface{} `json:"comments"`
	Commissions        struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"commissions"`
	CorrelatedCustomDate1      interface{} `json:"correlatedCustomDate1"`
	CorrelatedCustomDate2      interface{} `json:"correlatedCustomDate2"`
	CorrelatedCustomDate3      interface{} `json:"correlatedCustomDate3"`
	CorrelatedCustomFloat1     interface{} `json:"correlatedCustomFloat1"`
	CorrelatedCustomFloat2     interface{} `json:"correlatedCustomFloat2"`
	CorrelatedCustomFloat3     interface{} `json:"correlatedCustomFloat3"`
	CorrelatedCustomInt1       interface{} `json:"correlatedCustomInt1"`
	CorrelatedCustomInt2       interface{} `json:"correlatedCustomInt2"`
	CorrelatedCustomInt3       interface{} `json:"correlatedCustomInt3"`
	CorrelatedCustomText1      interface{} `json:"correlatedCustomText1"`
	CorrelatedCustomText10     interface{} `json:"correlatedCustomText10"`
	CorrelatedCustomText2      interface{} `json:"correlatedCustomText2"`
	CorrelatedCustomText3      interface{} `json:"correlatedCustomText3"`
	CorrelatedCustomText4      interface{} `json:"correlatedCustomText4"`
	CorrelatedCustomText5      interface{} `json:"correlatedCustomText5"`
	CorrelatedCustomText6      interface{} `json:"correlatedCustomText6"`
	CorrelatedCustomText7      interface{} `json:"correlatedCustomText7"`
	CorrelatedCustomText8      interface{} `json:"correlatedCustomText8"`
	CorrelatedCustomText9      interface{} `json:"correlatedCustomText9"`
	CorrelatedCustomTextBlock1 interface{} `json:"correlatedCustomTextBlock1"`
	CorrelatedCustomTextBlock2 interface{} `json:"correlatedCustomTextBlock2"`
	CorrelatedCustomTextBlock3 interface{} `json:"correlatedCustomTextBlock3"`
	CostCenter                 interface{} `json:"costCenter"`
	CustomBillRate1            interface{} `json:"customBillRate1"`
	CustomBillRate10           interface{} `json:"customBillRate10"`
	CustomBillRate2            interface{} `json:"customBillRate2"`
	CustomBillRate3            interface{} `json:"customBillRate3"`
	CustomBillRate4            interface{} `json:"customBillRate4"`
	CustomBillRate5            interface{} `json:"customBillRate5"`
	CustomBillRate6            interface{} `json:"customBillRate6"`
	CustomBillRate7            interface{} `json:"customBillRate7"`
	CustomBillRate8            interface{} `json:"customBillRate8"`
	CustomBillRate9            interface{} `json:"customBillRate9"`
	CustomDate1                interface{} `json:"customDate1"`
	CustomDate10               interface{} `json:"customDate10"`
	CustomDate11               interface{} `json:"customDate11"`
	CustomDate12               interface{} `json:"customDate12"`
	CustomDate13               interface{} `json:"customDate13"`
	CustomDate2                interface{} `json:"customDate2"`
	CustomDate3                interface{} `json:"customDate3"`
	CustomDate4                interface{} `json:"customDate4"`
	CustomDate5                interface{} `json:"customDate5"`
	CustomDate6                interface{} `json:"customDate6"`
	CustomDate7                interface{} `json:"customDate7"`
	CustomDate8                interface{} `json:"customDate8"`
	CustomDate9                interface{} `json:"customDate9"`
	CustomEncryptedText1       interface{} `json:"customEncryptedText1"`
	CustomEncryptedText10      interface{} `json:"customEncryptedText10"`
	CustomEncryptedText2       interface{} `json:"customEncryptedText2"`
	CustomEncryptedText3       interface{} `json:"customEncryptedText3"`
	CustomEncryptedText4       interface{} `json:"customEncryptedText4"`
	CustomEncryptedText5       interface{} `json:"customEncryptedText5"`
	CustomEncryptedText6       interface{} `json:"customEncryptedText6"`
	CustomEncryptedText7       interface{} `json:"customEncryptedText7"`
	CustomEncryptedText8       interface{} `json:"customEncryptedText8"`
	CustomEncryptedText9       interface{} `json:"customEncryptedText9"`
	CustomFloat1               interface{} `json:"customFloat1"`
	CustomFloat10              interface{} `json:"customFloat10"`
	CustomFloat11              interface{} `json:"customFloat11"`
	CustomFloat12              interface{} `json:"customFloat12"`
	CustomFloat13              interface{} `json:"customFloat13"`
	CustomFloat14              interface{} `json:"customFloat14"`
	CustomFloat15              interface{} `json:"customFloat15"`
	CustomFloat16              interface{} `json:"customFloat16"`
	CustomFloat17              interface{} `json:"customFloat17"`
	CustomFloat18              interface{} `json:"customFloat18"`
	CustomFloat19              interface{} `json:"customFloat19"`
	CustomFloat2               interface{} `json:"customFloat2"`
	CustomFloat20              interface{} `json:"customFloat20"`
	CustomFloat21              interface{} `json:"customFloat21"`
	CustomFloat22              interface{} `json:"customFloat22"`
	CustomFloat23              interface{} `json:"customFloat23"`
	CustomFloat3               interface{} `json:"customFloat3"`
	CustomFloat4               interface{} `json:"customFloat4"`
	CustomFloat5               interface{} `json:"customFloat5"`
	CustomFloat6               interface{} `json:"customFloat6"`
	CustomFloat7               interface{} `json:"customFloat7"`
	CustomFloat8               interface{} `json:"customFloat8"`
	CustomFloat9               interface{} `json:"customFloat9"`
	CustomInt1                 interface{} `json:"customInt1"`
	CustomInt10                interface{} `json:"customInt10"`
	CustomInt11                interface{} `json:"customInt11"`
	CustomInt12                interface{} `json:"customInt12"`
	CustomInt13                interface{} `json:"customInt13"`
	CustomInt14                interface{} `json:"customInt14"`
	CustomInt15                interface{} `json:"customInt15"`
	CustomInt16                interface{} `json:"customInt16"`
	CustomInt17                interface{} `json:"customInt17"`
	CustomInt18                interface{} `json:"customInt18"`
	CustomInt19                interface{} `json:"customInt19"`
	CustomInt2                 interface{} `json:"customInt2"`
	CustomInt20                interface{} `json:"customInt20"`
	CustomInt21                interface{} `json:"customInt21"`
	CustomInt22                interface{} `json:"customInt22"`
	CustomInt23                interface{} `json:"customInt23"`
	CustomInt3                 interface{} `json:"customInt3"`
	CustomInt4                 interface{} `json:"customInt4"`
	CustomInt5                 interface{} `json:"customInt5"`
	CustomInt6                 interface{} `json:"customInt6"`
	CustomInt7                 interface{} `json:"customInt7"`
	CustomInt8                 interface{} `json:"customInt8"`
	CustomInt9                 interface{} `json:"customInt9"`
	CustomPayRate1             interface{} `json:"customPayRate1"`
	CustomPayRate10            interface{} `json:"customPayRate10"`
	CustomPayRate2             interface{} `json:"customPayRate2"`
	CustomPayRate3             interface{} `json:"customPayRate3"`
	CustomPayRate4             interface{} `json:"customPayRate4"`
	CustomPayRate5             interface{} `json:"customPayRate5"`
	CustomPayRate6             interface{} `json:"customPayRate6"`
	CustomPayRate7             interface{} `json:"customPayRate7"`
	CustomPayRate8             interface{} `json:"customPayRate8"`
	CustomPayRate9             interface{} `json:"customPayRate9"`
	CustomText1                interface{} `json:"customText1"`
	CustomText10               interface{} `json:"customText10"`
	CustomText11               interface{} `json:"customText11"`
	CustomText12               interface{} `json:"customText12"`
	CustomText13               interface{} `json:"customText13"`
	CustomText14               interface{} `json:"customText14"`
	CustomText15               interface{} `json:"customText15"`
	CustomText16               interface{} `json:"customText16"`
	CustomText17               interface{} `json:"customText17"`
	CustomText18               interface{} `json:"customText18"`
	CustomText19               interface{} `json:"customText19"`
	CustomText2                interface{} `json:"customText2"`
	CustomText20               interface{} `json:"customText20"`
	CustomText21               interface{} `json:"customText21"`
	CustomText22               interface{} `json:"customText22"`
	CustomText23               interface{} `json:"customText23"`
	CustomText24               interface{} `json:"customText24"`
	CustomText25               interface{} `json:"customText25"`
	CustomText26               interface{} `json:"customText26"`
	CustomText27               interface{} `json:"customText27"`
	CustomText28               interface{} `json:"customText28"`
	CustomText29               interface{} `json:"customText29"`
	CustomText3                interface{} `json:"customText3"`
	CustomText30               interface{} `json:"customText30"`
	CustomText31               interface{} `json:"customText31"`
	CustomText32               interface{} `json:"customText32"`
	CustomText33               interface{} `json:"customText33"`
	CustomText34               interface{} `json:"customText34"`
	CustomText35               interface{} `json:"customText35"`
	CustomText36               interface{} `json:"customText36"`
	CustomText37               interface{} `json:"customText37"`
	CustomText38               interface{} `json:"customText38"`
	CustomText39               interface{} `json:"customText39"`
	CustomText4                interface{} `json:"customText4"`
	CustomText40               interface{} `json:"customText40"`
	CustomText41               interface{} `json:"customText41"`
	CustomText42               interface{} `json:"customText42"`
	CustomText43               interface{} `json:"customText43"`
	CustomText44               interface{} `json:"customText44"`
	CustomText45               interface{} `json:"customText45"`
	CustomText46               interface{} `json:"customText46"`
	CustomText47               interface{} `json:"customText47"`
	CustomText48               interface{} `json:"customText48"`
	CustomText49               interface{} `json:"customText49"`
	CustomText5                interface{} `json:"customText5"`
	CustomText50               interface{} `json:"customText50"`
	CustomText51               interface{} `json:"customText51"`
	CustomText52               interface{} `json:"customText52"`
	CustomText53               interface{} `json:"customText53"`
	CustomText54               interface{} `json:"customText54"`
	CustomText55               interface{} `json:"customText55"`
	CustomText56               interface{} `json:"customText56"`
	CustomText57               interface{} `json:"customText57"`
	CustomText58               interface{} `json:"customText58"`
	CustomText59               interface{} `json:"customText59"`
	CustomText6                interface{} `json:"customText6"`
	CustomText60               interface{} `json:"customText60"`
	CustomText7                interface{} `json:"customText7"`
	CustomText8                interface{} `json:"customText8"`
	CustomText9                interface{} `json:"customText9"`
	CustomTextBlock1           interface{} `json:"customTextBlock1"`
	CustomTextBlock10          interface{} `json:"customTextBlock10"`
	CustomTextBlock2           interface{} `json:"customTextBlock2"`
	CustomTextBlock3           interface{} `json:"customTextBlock3"`
	CustomTextBlock4           interface{} `json:"customTextBlock4"`
	CustomTextBlock5           interface{} `json:"customTextBlock5"`
	CustomTextBlock6           interface{} `json:"customTextBlock6"`
	CustomTextBlock7           interface{} `json:"customTextBlock7"`
	CustomTextBlock8           interface{} `json:"customTextBlock8"`
	CustomTextBlock9           interface{} `json:"customTextBlock9"`
	DateAdded                  int64       `json:"dateAdded"`
	DateBegin                  int64       `json:"dateBegin"`
	DateClientEffective        int64       `json:"dateClientEffective"`
	DateEffective              int64       `json:"dateEffective"`
	DateEnd                    interface{} `json:"dateEnd"`
	DateLastModified           int64       `json:"dateLastModified"`
	DaysGuaranteed             int         `json:"daysGuaranteed"`
	DaysProRated               int         `json:"daysProRated"`
	DurationWeeks              float64     `json:"durationWeeks"`
	EmployeeType               interface{} `json:"employeeType"`
	EmploymentStartDate        interface{} `json:"employmentStartDate"`
	EmploymentType             string      `json:"employmentType"`
	EstaffGUID                 interface{} `json:"estaffGUID"`
	ExpiringCredentials        int         `json:"expiringCredentials"`
	Fee                        float64     `json:"fee"`
	FileAttachments            struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"fileAttachments"`
	FlatFee          float64     `json:"flatFee"`
	HoursOfOperation interface{} `json:"hoursOfOperation"`
	HoursPerDay      float64     `json:"hoursPerDay"`
	HousingAmenities struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"housingAmenities"`
	HousingManagerID       interface{} `json:"housingManagerID"`
	HousingStatus          interface{} `json:"housingStatus"`
	IncompleteRequirements int         `json:"incompleteRequirements"`
	InvoiceGroupName       interface{} `json:"invoiceGroupName"`
	IsMultirate            bool        `json:"isMultirate"`
	IsWorkFromHome         interface{} `json:"isWorkFromHome"`
	JobOrder               struct {
		Id    int    `json:"id"`
		Title string `json:"title"`
	} `json:"jobOrder"`
	JobSubmission struct {
		Id int `json:"id"`
	} `json:"jobSubmission"`
	LastApprovedPlacementChangeRequest interface{} `json:"lastApprovedPlacementChangeRequest"`
	Location                           interface{} `json:"location"`
	MarkUpPercentage                   float64     `json:"markUpPercentage"`
	MigrateGUID                        interface{} `json:"migrateGUID"`
	Notes                              struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"notes"`
	OnboardingDocumentReceivedCount int `json:"onboardingDocumentReceivedCount"`
	OnboardingDocumentSentCount     int `json:"onboardingDocumentSentCount"`
	OnboardingPercentComplete       int `json:"onboardingPercentComplete"`
	OnboardingReceivedSent          struct {
		OnboardingDocumentReceivedCount int `json:"onboardingDocumentReceivedCount"`
		OnboardingDocumentSentCount     int `json:"onboardingDocumentSentCount"`
	} `json:"onboardingReceivedSent"`
	OnboardingStatus         interface{} `json:"onboardingStatus"`
	OptionsPackage           interface{} `json:"optionsPackage"`
	OtExemption              interface{} `json:"otExemption"`
	OtherHourlyFee           interface{} `json:"otherHourlyFee"`
	OtherHourlyFeeComments   interface{} `json:"otherHourlyFeeComments"`
	OvertimeMarkUpPercentage float64     `json:"overtimeMarkUpPercentage"`
	OvertimeRate             interface{} `json:"overtimeRate"`
	Owner                    struct {
		Id        int    `json:"id"`
		FirstName string `json:"firstName"`
		LastName  string `json:"lastName"`
	} `json:"owner"`
	Owners struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"owners"`
	PayGroup                interface{} `json:"payGroup"`
	PayRate                 float64     `json:"payRate"`
	PayrollEmployeeType     interface{} `json:"payrollEmployeeType"`
	PayrollSyncStatus       interface{} `json:"payrollSyncStatus"`
	PendingChangeRequests   int         `json:"pendingChangeRequests"`
	PlacementCertifications struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"placementCertifications"`
	PositionCode                        interface{} `json:"positionCode"`
	ProjectCodeList                     interface{} `json:"projectCodeList"`
	QuitJob                             bool        `json:"quitJob"`
	RecruitingManagerPercentGrossMargin float64     `json:"recruitingManagerPercentGrossMargin"`
	ReferralFee                         float64     `json:"referralFee"`
	ReferralFeeType                     string      `json:"referralFeeType"`
	ReportTo                            interface{} `json:"reportTo"`
	ReportedMargin                      float64     `json:"reportedMargin"`
	Salary                              float64     `json:"salary"`
	SalaryUnit                          string      `json:"salaryUnit"`
	SalesManagerPercentGrossMargin      float64     `json:"salesManagerPercentGrossMargin"`
	Shift                               interface{} `json:"shift"`
	StatementClientContact              interface{} `json:"statementClientContact"`
	Status                              string      `json:"status"`
	Tasks                               struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"tasks"`
	TaxRate           float64     `json:"taxRate"`
	TaxState          interface{} `json:"taxState"`
	TerminationReason interface{} `json:"terminationReason"`
	TimeUnits         struct {
		Total int           `json:"total"`
		Data  []interface{} `json:"data"`
	} `json:"timeUnits"`
	VendorClientCorporation interface{} `json:"vendorClientCorporation"`
	WorkWeekStart           interface{} `json:"workWeekStart"`
	WorkersCompensationRate interface{} `json:"workersCompensationRate"`
}
